# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: self-hosted
    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: tsc
      working-directory: ./var/www/stockify.de/stockify-landing
    - run: npm ci
      working-directory: ./var/www/stockify.de/stockify-landing
    - run: npm run build --if-present
      working-directory: ./var/www/stockify.de/stockify-landing
    - run: npm test
      working-directory: ./var/www/stockify.de/stockify-landing
