# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: stockify-landing

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: self-hosted
    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm i
    - run: tsc
    - run: CI=false npm run build
    - run: ls
    - run: mv /development/actions-runner/stockify-landing-runner/stockify-landing/stockify-landing/public/* /var/www/stockify.de/stockify-landing/public/
    

